version: '3.8'

services:
  flask-server:
    build:
      context: ./gsrv
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    build:
      context: ./psql
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
